
# File to execute compiler specific commands

SET(COMPILER_INCLUDES "" CACHE INTERNAL "Compiler specific includes")
SET(COMPILER_LBRARIES "" CACHE INTERNAL "Compiler specific libraries")

IF (MSVC)
	INCLUDE(msvc)
ELSE(MSVC)
	MESSAGE(STATUS "No special handling for this compiler present, good luck!")
	
	IF (NOT FSO_INSTRUCTION_SET STREQUAL "")
		MESSAGE(WARNING "This compiler does not support a special instruction set!")
	
		SET(FSO_INSTRUCTION_SET "")
	ENDIF(NOT FSO_INSTRUCTION_SET STREQUAL "")
ENDIF(MSVC)

IF (WIN32)
	ADD_DEFINITIONS(-DWIN32)
	ADD_DEFINITIONS(-DUSE_OPENAL)
	ADD_DEFINITIONS(-D_SECURE_SCL=0)
	ADD_DEFINITIONS(-D_HAS_ITERATOR_DEBUGGING=0)
ENDIF(WIN32)

IF(NOT FSO_INSTRUCTION_SET STREQUAL "")
	ADD_DEFINITIONS(_D_${FSO_INSTRUCTION_SET})
ENDIF(NOT FSO_INSTRUCTION_SET STREQUAL "")
