
IF("${FSO_VERSION_BUILD}" STREQUAL "")

  IF ("${FSO_INSTRUCTION_SET}" STREQUAL "")
    SET(FSO_BINARY_SUFFIX "${FSO_VERSION_MAJOR}_${FSO_VERSION_MINOR}_${FSO_VERSION_BUILD}")
  ELSE("${FSO_INSTRUCTION_SET}" STREQUAL "")
    SET(FSO_BINARY_SUFFIX "${FSO_VERSION_MAJOR}_${FSO_VERSION_MINOR}_${FSO_VERSION_BUILD}-${FSO_INSTRUCTION_SET}")
  ENDIF("${FSO_INSTRUCTION_SET}" STREQUAL "")
  
ELSE("${FSO_VERSION_BUILD}" STREQUAL "")

  IF ("${FSO_INSTRUCTION_SET}" STREQUAL "")
    SET(FSO_BINARY_SUFFIX "${FSO_VERSION_MAJOR}_${FSO_VERSION_MINOR}_${FSO_VERSION_BUILD}")
  ELSE("${FSO_INSTRUCTION_SET}" STREQUAL "")
    SET(FSO_BINARY_SUFFIX "${FSO_VERSION_MAJOR}_${FSO_VERSION_MINOR}_${FSO_VERSION_BUILD}_${FSO_INSTRUCTION_SET}")
  ENDIF("${FSO_INSTRUCTION_SET}" STREQUAL "")
  
ENDIF("${FSO_VERSION_BUILD}" STREQUAL "")

IF (NOT "${FSO_BUILD_POSTFIX}" STREQUAL "")
    SET(FSO_BINARY_SUFFIX "${FSO_VERSION_MAJOR}_${FSO_VERSION_MINOR}_${FSO_VERSION_BUILD}_${FSO_INSTRUCTION_SET}-${FSO_BUILD_POSTFIX}")
ENDIF(NOT "${FSO_BUILD_POSTFIX}" STREQUAL "")

SET(BINARY_DESTINATION ".")