IF (FSO_INSTRUCTION_SET STREQUAL "")
	SET(FSO_BINARY_SUFFIX "${FSO_VERSION_MAJOR}_${FSO_VERSION_MINOR}_${FSO_VERSION_BUILD}")
ELSE(FSO_INSTRUCTION_SET STREQUAL "")
	SET(FSO_BINARY_SUFFIX "${FSO_VERSION_MAJOR}_${FSO_VERSION_MINOR}_${FSO_VERSION_BUILD}_${FSO_INSTRUCTION_SET}")
ENDIF(FSO_INSTRUCTION_SET STREQUAL "")

SET(BINARY_DESTINATION ".")