
MESSAGE(STATUS "Doing configuration specific to visual studio...")

INCLUDE(util)

# Disable SAFESEH for visual studio
ADD_LINKER_FLAG("/SAFESEH:NO")

ADD_LINKER_FLAG("/NODEFAULTLIB:libc.lib /NODEFAULTLIB:libcd.lib /NODEFAULTLIB:libcmt.lib /NODEFAULTLIB:libci.lib")

# Set runtime library
REPLACE_COMPILER_FLAG("/MD" "/MT")

# Set /EHsc
ADD_COMPILER_FLAG("/EHsc" "/EHsc")

IF (NOT FSO_INSTRUCTION_SET STREQUAL "")
	ADD_COMPILER_FLAG("/arch:${FSO_INSTRUCTION_SET}" "/arch:${FSO_INSTRUCTION_SET}")
ENDIF(NOT FSO_INSTRUCTION_SET STREQUAL "")

OPTION(FSO_ENABLE_PDB_DEBUGGING "Enable or disable PDB debugging" ON)
MARK_AS_ADVANCED(FORCE FSO_ENABLE_PDB_DEBUGGING)

IF(FSO_ENABLE_PDB_DEBUGGING)
	ADD_DEFINITIONS(-DPDB_DEBUGGING)
ENDIF(FSO_ENABLE_PDB_DEBUGGING)
