
INCLUDE(util)

MESSAGE(STATUS "Configuring UNIX specific things and stuff...")

FIND_PACKAGE(SDL REQUIRED)

SET(PLATFORM_INCLUDES ${PLATFORM_INCLUDES} ${SDL_INCLUDE_DIR} CACHE INTERNAL "")
SET(PLATFORM_LBRARIES ${PLATFORM_LBRARIES} ${SDL_LIBRARY} CACHE INTERNAL "")

ADD_DEFINITIONS(-DSCP_UNIX)
ADD_DEFINITIONS(-DUSE_OPENAL)

FIND_PACKAGE(OpenGL REQUIRED)

SET(PLATFORM_INCLUDES ${PLATFORM_INCLUDES} ${OPENGL_INCLUDE_DIR})
SET(PLATFORM_LBRARIES ${PLATFORM_LBRARIES} ${OPENGL_LIBRARY})

# Also add dynamic linking libs
CMAKE_SEARCH_LIBS(HAVE_DLSYM LIB_DLSYM dlsym dl)

IF(HAVE_DLSYM)
	SET(PLATFORM_LBRARIES ${PLATFORM_LBRARIES} ${LIB_DLSYM})
ELSE(HAVE_DLSYM)
	MESSAGE(FATAL_ERROR "Failed to find library providing dlsym!")
ENDIF(HAVE_DLSYM)

