
INCLUDE(util)

MESSAGE(STATUS "Configuring UNIX specific things and stuff...")

IF(APPLE)
	FIND_PACKAGE(SDL)
	
	IF(NOT SDL_FOUND)
		MESSAGE(STATUS "SDL not found: Using included SDL libraries")
		SET(FSO_USE_SDL_FRAMEWORK ON CACHE INTERNAL "") # We ship these for mac
	ENDIF(NOT SDL_FOUND)
ELSE(APPLE)
	FIND_PACKAGE(SDL REQUIRED)
ENDIF(APPLE)

IF(NOT FSO_USE_SDL_FRAMEWORK)
	SET(PLATFORM_INCLUDES ${PLATFORM_INCLUDES} ${SDL_INCLUDE_DIR} CACHE INTERNAL "")
	SET(PLATFORM_LBRARIES ${PLATFORM_LBRARIES} ${SDL_LIBRARY} CACHE INTERNAL "")
ENDIF(NOT FSO_USE_SDL_FRAMEWORK)

ADD_DEFINITIONS(-DSCP_UNIX)
ADD_DEFINITIONS(-DUSE_OPENAL)

FIND_PACKAGE(OpenGL REQUIRED)

SET(PLATFORM_INCLUDES ${PLATFORM_INCLUDES} ${OPENGL_INCLUDE_DIR})
SET(PLATFORM_LBRARIES ${PLATFORM_LBRARIES} ${OPENGL_LIBRARY})

IF(APPLE)
	include(platform-mac)
ELSE(APPLE)
	SET(EXE_GUI_TYPE)
ENDIF(APPLE)

