
MESSAGE(STATUS "Configuring UNIX specific things and stuff...")

FIND_PACKAGE(SDL REQUIRED)

SET(PLATFORM_INCLUDES ${PLATFORM_INCLUDES} ${SDL_INCLUDE_DIR} CACHE INTERNAL "")
SET(PLATFORM_LBRARIES ${PLATFORM_LBRARIES} ${SDL_LIBRARY} CACHE INTERNAL "")

ADD_DEFINITIONS(-DSCP_UNIX)
ADD_DEFINITIONS(-DUSE_OPENAL)
