
MACRO(REPLACE_COMPILER_FLAG ORIGIGNAL REPLACEMENT)
	set(REPLACE_COMPILER_FLAG_variables
	  CMAKE_C_FLAGS_DEBUG
	  CMAKE_C_FLAGS_MINSIZEREL
	  CMAKE_C_FLAGS_RELEASE
	  CMAKE_C_FLAGS_RELWITHDEBINFO
	  CMAKE_CXX_FLAGS_DEBUG
	  CMAKE_CXX_FLAGS_MINSIZEREL
	  CMAKE_CXX_FLAGS_RELEASE
	  CMAKE_CXX_FLAGS_RELWITHDEBINFO
	)
	
	FOREACH(variable ${REPLACE_COMPILER_FLAG_variables})
		STRING(REPLACE ${ORIGIGNAL} ${REPLACEMENT} ${variable} "${${variable}}")
		SET(${variable} ${${variable}})
	ENDFOREACH()	
ENDMACRO(REPLACE_COMPILER_FLAG)

FUNCTION(MAKE_CACHE_INTERNAL VARIABLE)
	SET(${VARIABLE} ${${VARIABLE}} CACHE INTERNAL "Internal cache variable")
ENDFUNCTION(MAKE_CACHE_INTERNAL)

FUNCTION(ADD_COMPILER_FLAG RELEASE DEBUG)	
	SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS_DEBUG} ${RELEASE}" PARENT_SCOPE)
	SET(CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG} ${DEBUG}" PARENT_SCOPE)
	SET(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} ${RELEASE}" PARENT_SCOPE)
	SET(CMAKE_CXX_FLAGS_RELWITHDEBINFO "${CMAKE_CXX_FLAGS_RELWITHDEBINFO} ${RELEASE}" PARENT_SCOPE)
	SET(CMAKE_CXX_FLAGS_MINSIZEREL "${CMAKE_CXX_FLAGS_MINSIZEREL} ${RELEASE}" PARENT_SCOPE)
	
	SET(CMAKE_C_FLAGS "${CMAKE_CXX_FLAGS_DEBUG} ${RELEASE}" PARENT_SCOPE)
	SET(CMAKE_C_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG} ${DEBUG}" PARENT_SCOPE)
	SET(CMAKE_C_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} ${RELEASE}" PARENT_SCOPE)
	SET(CMAKE_C_FLAGS_RELWITHDEBINFO "${CMAKE_CXX_FLAGS_RELWITHDEBINFO} ${RELEASE}" PARENT_SCOPE)
	SET(CMAKE_C_FLAGS_MINSIZEREL "${CMAKE_CXX_FLAGS_MINSIZEREL} ${RELEASE}" PARENT_SCOPE)
ENDFUNCTION(ADD_COMPILER_FLAG)

FUNCTION(ADD_LINKER_FLAG FLAG)
	SET (CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} ${FLAG}" PARENT_SCOPE)
	SET (CMAKE_SHARED_LINKER_FLAGS "${CMAKE_SHARED_LINKER_FLAGS} ${FLAG}" PARENT_SCOPE)
	SET (CMAKE_MODULE_LINKER_FLAGS "${CMAKE_MODULE_LINKER_FLAGS} ${FLAG}" PARENT_SCOPE)
ENDFUNCTION(ADD_LINKER_FLAG)

