
macro(set_if_not_defined VAR VALUE)
    if (NOT DEFINED ${VAR})
        set(${VAR} ${VALUE})
    endif()
endmacro(set_if_not_defined)

set_if_not_defined(FSO_VERSION_MAJOR 3)
set_if_not_defined(FSO_VERSION_MINOR 7)
set_if_not_defined(FSO_VERSION_BUILD 3)

# A generic revision string, can be anything
set_if_not_defined(FSO_VERSION_REVISION "")

# A numeric revision e.g. the CI build number
set_if_not_defined(FSO_VERSION_REVISION_NUM 0)

if("${FSO_VERSION_REVISION}" STREQUAL "")
    set(FSO_VERSION_HAS_REVISION 0)
else()
    set(FSO_VERSION_HAS_REVISION 1)
endif()

set(FSO_FULL_VERSION_STRING "${FSO_VERSION_MAJOR}.${FSO_VERSION_MINOR}.${FSO_VERSION_BUILD}")

if (NOT "${FSO_VERSION_REVISION}" STREQUAL "")
    set(FSO_FULL_VERSION_STRING "${FSO_FULL_VERSION_STRING}.${FSO_VERSION_REVISION}")
endif()

IF("${FSO_VERSION_REVISION}" STREQUAL "")
    SET(FSO_BINARY_SUFFIX "${FSO_VERSION_MAJOR}_${FSO_VERSION_MINOR}_${FSO_VERSION_BUILD}")
ELSE()
    SET(FSO_BINARY_SUFFIX "${FSO_VERSION_MAJOR}_${FSO_VERSION_MINOR}_${FSO_VERSION_BUILD}_${FSO_VERSION_REVISION}")
ENDIF()

IF (NOT "${FSO_INSTRUCTION_SET}" STREQUAL "")
    SET(FSO_BINARY_SUFFIX "${FSO_BINARY_SUFFIX}_${FSO_INSTRUCTION_SET}")
ENDIF()

IF (NOT "${FSO_BUILD_POSTFIX}" STREQUAL "")
    SET(FSO_BINARY_SUFFIX "${FSO_BINARY_SUFFIX}_${FSO_BUILD_POSTFIX}")
ENDIF()
